services:
  parkingapi:
    image: ${DOCKER_REGISTRY-}parkingapi
    build:
      context: .
      dockerfile: ParkingApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  mssql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=superSecurePassword!
    ports:
      - 1433:1433